name: tarameteo

services:
  api:
    volumes:
      - ./backend/tarameteo:/app/tarameteo
    command: uvicorn --host=0.0.0.0 --port=80 tarameteo.api:app --log-config=/app/log-config.dev.yaml --reload --reload-exclude='.*'

  ca:
    volumes:
      - ./backend/tarameteo:/app/tarameteo
    command: uvicorn --host=0.0.0.0 --port=80 tarameteo.ca:app --log-config=/app/log-config.dev.yaml --reload --reload-exclude='.*'

  certbot:
    depends_on:
      ca-init:
        condition: service_completed_successfully
    volumes:
      - ./taracert/generate-cert.sh:/generate-cert.sh:ro
      - ca-tls:/tls:ro
    environment:
      CA_CERT_PATH: /tls/ca.pem
      CA_KEY_PATH: /tls/ca.key
    command:
      - sh
      - -ec
      - |
        trap 'exit 0' TERM
        /generate-cert.sh
        /deploy-hook.sh
        echo Ready
        sleep infinity
  mosquitto:
    networks:
      default:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.241

  sources:
    volumes:
      - ./backend/tarameteo:/app/tarameteo

  mosquitto-init:
    command:
      - sh
      - -ec
      - |
        tarameteo-pki rotate mosquitto --san-dns tarameteo-mosquitto --san-dns ${SERVER_HOSTNAME} --san-ip ${IPV4_NETWORK:-172.22.1}.241
        chown -R 1883:1883 /tls
