[project]
name = "tarameteo"
version = "0.0.0"
description = "Weather station API"
authors = [
    {name = "Marc Tardif", email = "marc@taram.ca"},
]
readme = "README.rst"

requires-python = ">=3.12,<4.0"
dependencies = [
    "attrs>=26.1.0",
    "configargparse>=1.7.1,<2.0.0",
    "cryptography>=48.0.0,<48.1.0",
    "fastapi>=0.109.0",
    "influxdb-client>=1.49.0,<2.0.0",
    "beautifulsoup4>=4.12.0,<5.0.0",
    "httpx>=0.28.1,<0.29.0",
    "more-itertools>=11.0.1,<11.1.0",
    "pydantic>=2.12.3,<3.0.0",
    "uvicorn[standard]>=0.34.0,<1.0.0",
    "paho-mqtt>=2.1.0,<3.0.0",
    "watchdog>=6.0.0,<7.0.0",
    "taraqueue>=0.5.0",
    "yarl>=1.22.0,<2.0.0",
]

[project.optional-dependencies]

test = [
    "coverage>=7.2.3,<8.0.0",
    "pyhamcrest>=2.1.0,<3.0.0",
    "pytest>=9.0.0,<10.0.0",
    "pytest-asyncio>=1.3.0,<2.0.0",
    "pytest-unique>=0.1.8,<1.0.0",
    "pytest-xdocker>=0.2.8,<1.0.0",
]

check = [
  "ruff>=0.15.0,<1.0.0",
]

[project.entry-points."tarameteo_source"]
melccfp = "tarameteo.melccfp"
metar = "tarameteo.metar"
msc = "tarameteo.msc"

[project.entry-points."pytest11"]
tarameteo = "tarameteo.testing.fixtures"
tarameteo-services = "tarameteo.testing.services"

[project.entry-points."pytest_unique"]
subject = "tarameteo.testing.unique:unique_subject"

[project.scripts]
tarameteo-consumer = "tarameteo.consumer:main"
tarameteo-pki = "tarameteo.pki_cli:main"
tarameteo-sources = "tarameteo.sources:main"

[project.urls]
Repository = "https://github.com/taradix/tarameteo"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py312"
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
    # Create your own exception
    "TRY002",
    # Avoid specifying long messages outside the exception class
    "TRY003",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "S106"]

# Pytest options:
#   https://docs.pytest.org/en/6.2.x/reference.html#ini-options-ref
[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = [
    "--doctest-modules",
    "--doctest-glob=*.rst",
]
testpaths = [
    "tarameteo",
    "tests",
]

# Coverage options:
#   https://coverage.readthedocs.io/en/latest/config.html
[tool.coverage.paths]
source = [
    "tarameteo",
    "*/*/site-packages",
]

[tool.coverage.report]
fail_under = 70
show_missing = true

[tool.coverage.run]
branch = true
parallel = true
source = [
    "tarameteo",
]
