"""add alerts table

Revision ID: a41f56e76d2e
Revises:
Create Date: 2026-05-22 18:45:42.772213

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a41f56e76d2e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sensor', sa.String(length=255), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_email', 'alerts', ['email'], unique=False)
    op.create_index('idx_alerts_sensor_confirmed', 'alerts', ['sensor', 'confirmed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alerts_sensor_confirmed', table_name='alerts')
    op.drop_index('idx_alerts_email', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
