#include "CertificateManager.h"
#include "X509Parser.h"

#include <ArduinoJson.h>
#include <stdio.h>
#include <string.h>

#ifdef UNIT_TEST
#include "Arduino.h"
// Forward declaration for unit tests
class WiFiManager;
#else
#include "WiFiManager.h"
#endif

static const int SECONDS_PER_DAY = 24 * 60 * 60;

CertificateManager::CertificateManager(Preferences &prefs, IWiFi *wifi, IArduino *arduino)
    : _prefs(prefs), _wifi(wifi), _arduino(arduino), _expiresAt(0), _certVersion(0), _provisioningActive(false),
      _provisioningStartTime(0), _provisioningServer(nullptr), _wifiManager(nullptr), _clientCert(nullptr),
      _clientKey(nullptr), _caCert(nullptr), _latitude(0.0f), _longitude(0.0f) {
  _lastError[0] = '\0';
  _cn[0] = '\0';
}

CertificateManager::~CertificateManager() {
  stopProvisioningMode();
  clearClientCredentials();
  clearCACertificate();
}

bool CertificateManager::begin() {
  _arduino->log("CertificateManager: Initializing...");

  // Initialize NVS
  if (!_prefs.begin("tarameteo_certs", false)) {
    setError("Failed to initialize NVS");
    return false;
  }

  // Try to load existing certificates from NVS
  if (loadFromNVS()) {
    _arduino->log("CertificateManager: Certificates loaded from NVS");

    // Validate loaded certificates
    if (validateCertificates()) {
      _arduino->log("CertificateManager: Certificates validated successfully");
      return true;
    } else {
      _arduino->log("CertificateManager: Certificate validation failed, clearing invalid certificates");
      clearClientCredentials();
      clearCACertificate();
    }
  }

  // NVS empty — try loading from embedded (pre-flashed) certificates
  if (loadFromEmbedded()) {
    _arduino->log("CertificateManager: Certificates installed from embedded flash");
    if (validateCertificates()) {
      _arduino->log("CertificateManager: Embedded certificates validated successfully");
      return true;
    } else {
      _arduino->log("CertificateManager: Embedded certificate validation failed");
    }
  }

  // No certificates found or invalid
  if (needsProvisioning()) {
    _arduino->log("CertificateManager: Certificates not found - provisioning needed");
    return false;
  }

  return true;
}

bool CertificateManager::isProvisioned() const { return (_clientCert != nullptr && _clientKey != nullptr); }

bool CertificateManager::needsProvisioning() const { return !isProvisioned(); }

bool CertificateManager::loadFromNVS() {
  if (!_prefs.isKey("cli_cert") || !_prefs.isKey("cli_key")) {
    setError("Certificates not found in NVS");
    return false;
  }

  if (!_clientCert) {
    _clientCert = (char *)malloc(MAX_CERT_SIZE);
  }
  if (!_clientKey) {
    _clientKey = (char *)malloc(MAX_KEY_SIZE);
  }
  if (!_clientCert || !_clientKey) {
    clearClientCredentials();
    setError("Failed to allocate memory for certificates");
    return false;
  }

  size_t certLen = _prefs.getString("cli_cert", _clientCert, MAX_CERT_SIZE);
  if (certLen == 0) {
    clearClientCredentials();
    setError("Failed to read client certificate from NVS");
    return false;
  }

  size_t keyLen = _prefs.getString("cli_key", _clientKey, MAX_KEY_SIZE);
  if (keyLen == 0) {
    clearClientCredentials();
    setError("Failed to read client key from NVS");
    return false;
  }

  if (_prefs.isKey("ca_cert")) {
    clearCACertificate();
    _caCert = (char *)malloc(MAX_CERT_SIZE);
    if (_caCert) {
      size_t caLen = _prefs.getString("ca_cert", _caCert, MAX_CERT_SIZE);
      if (caLen == 0) {
        clearCACertificate();
      }
    }
  }

  _prefs.getString("cert_cn", _cn, MAX_CN_LENGTH);
  _expiresAt = _prefs.getULong("cert_expires", 0);
  _certVersion = _prefs.getInt("cert_version", 0);
  _latitude = _prefs.getFloat("latitude", 0.0f);
  _longitude = _prefs.getFloat("longitude", 0.0f);

  _arduino->logf("CertificateManager: Loaded cert CN=%s, expires=%lu, version=%d, lat=%.6f, lon=%.6f",
                 _cn, _expiresAt, _certVersion, _latitude, _longitude);

  return true;
}

bool CertificateManager::loadFromEmbedded() {
#ifndef UNIT_TEST
  // Symbols generated by board_build.embed_txtfiles in platformio.ini.
  // PlatformIO null-terminates text files, so these are valid C strings.
  extern const char _binary_certs_client_pem_start[];
  extern const char _binary_certs_client_key_start[];
  extern const char _binary_certs_ca_pem_start[];

  const char *certPem = _binary_certs_client_pem_start;
  const char *keyPem = _binary_certs_client_key_start;
  const char *caPem = _binary_certs_ca_pem_start;

  if (!certPem || strlen(certPem) == 0 || !keyPem || strlen(keyPem) == 0) {
    _arduino->log("CertificateManager: No embedded certificates found");
    return false;
  }

  _arduino->log("CertificateManager: Loading certificates from embedded flash...");

  // Store embedded certs into NVS so subsequent boots use loadFromNVS()
  if (!storeCertificates(certPem, keyPem, (caPem && strlen(caPem) > 0) ? caPem : nullptr)) {
    _arduino->log("CertificateManager: Failed to store embedded certs to NVS");
    return false;
  }

  return true;
#else
  // In unit tests, embedded symbols don't exist
  return false;
#endif
}

bool CertificateManager::saveToNVS(const char *certPem, const char *keyPem, const char *caCertPem) {
  _arduino->log("CertificateManager: Saving certificates to NVS");

  if (_prefs.putString("cli_cert", certPem) == 0) {
    setError("Failed to save client certificate");
    return false;
  }

  if (_prefs.putString("cli_key", keyPem) == 0) {
    setError("Failed to save client key");
    return false;
  }

  if (caCertPem && strlen(caCertPem) > 0) {
    _prefs.putString("ca_cert", caCertPem);
  }

  _prefs.putString("cert_cn", _cn);
  _prefs.putULong("cert_expires", _expiresAt);
  _prefs.putInt("cert_version", _certVersion);
  _prefs.putFloat("latitude", _latitude);
  _prefs.putFloat("longitude", _longitude);

  _arduino->log("CertificateManager: Certificates saved successfully");
  return true;
}

bool CertificateManager::loadCertificates(IWiFiClient &client) {
  if (!isProvisioned()) {
    setError("Certificates not provisioned");
    return false;
  }

  if (_caCert) {
    client.setCACert(_caCert);
    _arduino->log("CertificateManager: CA certificate loaded");
  } else {
    setError("CA certificate is required for TLS server verification");
    return false;
  }

  client.setCertificate(_clientCert);
  client.setPrivateKey(_clientKey);

  _arduino->logf("CertificateManager: Client certificate loaded (CN=%s)", _cn);
  return true;
}

bool CertificateManager::validateCertificates() {
  if (!isProvisioned()) {
    setError("Certificates not provisioned");
    return false;
  }

  if (!validateCertificateFormat(_clientCert)) {
    setError("Invalid certificate format");
    return false;
  }

  if (!validatePrivateKeyFormat(_clientKey)) {
    setError("Invalid private key format");
    return false;
  }

  if (!extractCNFromCert(_clientCert)) {
    setError("Failed to extract CN from certificate");
    return false;
  }

  if (!extractExpirationFromCert(_clientCert)) {
    _arduino->log("CertificateManager: WARNING - Failed to extract expiration date");
  } else {
    unsigned long now = _arduino->currentEpochSeconds();
    if (now < SECONDS_PER_DAY) {
      setError("Current time unavailable for certificate validation");
      return false;
    }

    // Check if certificate is expired or expiring soon
    if (_expiresAt > 0 && _expiresAt < now) {
      setError("Certificate has expired");
      return false;
    } else if (_expiresAt > 0 && (_expiresAt - now) < (CERT_EXPIRY_WARNING_DAYS * SECONDS_PER_DAY)) {
      unsigned long daysLeft = (_expiresAt - now) / SECONDS_PER_DAY;
      _arduino->logf("CertificateManager: WARNING - Certificate expires in %lu days", daysLeft);
    }
  }

  #ifdef DEBUG_CERTS
  char certInfo[1024];
  if (X509Parser::getCertificateInfo(_clientCert, certInfo, sizeof(certInfo))) {
    _arduino->log("Certificate details:");
    _arduino->log(certInfo);
  }
  #endif

  return true;
}

bool CertificateManager::validateCertificateFormat(const char *certPem) {
  if (!certPem || strlen(certPem) == 0) {
    return false;
  }

  if (strstr(certPem, "-----BEGIN CERTIFICATE-----") == nullptr) {
    return false;
  }
  if (strstr(certPem, "-----END CERTIFICATE-----") == nullptr) {
    return false;
  }

  return true;
}

bool CertificateManager::validatePrivateKeyFormat(const char *keyPem) {
  if (!keyPem || strlen(keyPem) == 0) {
    return false;
  }

  bool hasBegin = (strstr(keyPem, "-----BEGIN PRIVATE KEY-----") != nullptr) ||
                  (strstr(keyPem, "-----BEGIN RSA PRIVATE KEY-----") != nullptr) ||
                  (strstr(keyPem, "-----BEGIN EC PRIVATE KEY-----") != nullptr);

  bool hasEnd = (strstr(keyPem, "-----END PRIVATE KEY-----") != nullptr) ||
                (strstr(keyPem, "-----END RSA PRIVATE KEY-----") != nullptr) ||
                (strstr(keyPem, "-----END EC PRIVATE KEY-----") != nullptr);

  return (hasBegin && hasEnd);
}

bool CertificateManager::extractCNFromCert(const char *certPem) {
  bool result = X509Parser::extractCN(certPem, _cn, MAX_CN_LENGTH);

  if (!result) {
    _arduino->log("CertificateManager: Failed to extract CN from certificate");
    return false;
  }

  _arduino->logf("CertificateManager: Extracted CN: %s", _cn);
  return true;
}

bool CertificateManager::extractExpirationFromCert(const char *certPem) {
  bool result = X509Parser::extractExpiration(certPem, &_expiresAt);

  if (!result) {
    _arduino->log("CertificateManager: WARNING - Failed to extract expiration date");
    _expiresAt = 0;
    return false;
  }

  // Log expiration date for debugging
  unsigned long now = _arduino->currentEpochSeconds();
  if (now >= SECONDS_PER_DAY) {
    long daysUntilExpiry = (_expiresAt - now) / SECONDS_PER_DAY;
    _arduino->logf("CertificateManager: Certificate expires in %ld days", daysUntilExpiry);
  } else {
    _arduino->logf("CertificateManager: Certificate expiration epoch=%lu", _expiresAt);
  }

  return true;
}

bool CertificateManager::validateCertKeyPair(const char *certPem, const char *keyPem) {
  // First validate PEM format
  if (!validateCertificateFormat(certPem)) {
    _arduino->log("CertificateManager: Invalid certificate format");
    return false;
  }

  if (!validatePrivateKeyFormat(keyPem)) {
    _arduino->log("CertificateManager: Invalid private key format");
    return false;
  }

  // Then verify cryptographic match
  _arduino->log("CertificateManager: Validating certificate/key pair...");
  bool result = X509Parser::validateKeyPair(certPem, keyPem);

  if (!result) {
    _arduino->log("CertificateManager: ERROR - Certificate and private key do not match!");
    return false;
  }

  _arduino->log("CertificateManager: Certificate/key pair validated successfully");
  return true;
}

void CertificateManager::logCertificateInfo(const char* certPem) {
  char info[512];
  if (X509Parser::getCertificateInfo(certPem, info, sizeof(info))) {
    _arduino->log("Certificate Information:");
    _arduino->log(info);
  }
}

bool CertificateManager::storeCertificates(const char *certPem, const char *keyPem, const char *caCertPem) {
  _arduino->log("CertificateManager: Storing certificates");

  // Validate formats
  if (!validateCertificateFormat(certPem)) {
    setError("Invalid certificate format");
    return false;
  }

  if (!validatePrivateKeyFormat(keyPem)) {
    setError("Invalid private key format");
    return false;
  }

  if (!validateCertKeyPair(certPem, keyPem)) {
    setError("Certificate and key do not match");
    return false;
  }

  #ifdef DEBUG_CERTIFICATES
  logCertificateInfo(certPem);
  #endif

  // Allocate and store in memory
  if (_clientCert)
    free(_clientCert);
  if (_clientKey)
    free(_clientKey);
  if (_caCert)
    free(_caCert);

  _clientCert = (char *)malloc(strlen(certPem) + 1);
  _clientKey = (char *)malloc(strlen(keyPem) + 1);

  if (!_clientCert || !_clientKey) {
    setError("Failed to allocate memory");
    return false;
  }

  strcpy(_clientCert, certPem);
  strcpy(_clientKey, keyPem);

  if (caCertPem && strlen(caCertPem) > 0) {
    _caCert = (char *)malloc(strlen(caCertPem) + 1);
    if (_caCert) {
      strcpy(_caCert, caCertPem);
    }
  } else {
    _caCert = nullptr;
  }

  // Extract CN and set metadata
  if (!extractCNFromCert(certPem)) {
    setError("Failed to extract CN from certificate");
    return false;
  }

  if (X509Parser::extractSerial(certPem, _serialNumber, sizeof(_serialNumber))) {
    _arduino->logf("Certificate serial: %s", _serialNumber);
  }

  extractExpirationFromCert(certPem);
  _certVersion++;

  // Save to NVS
  if (!saveToNVS(certPem, keyPem, caCertPem)) {
    return false;
  }

  _arduino->log("CertificateManager: Certificates stored successfully");
  return true;
}

bool CertificateManager::clearCertificates() {
  _arduino->log("CertificateManager: Clearing certificates");

  _prefs.clear();

  if (_clientCert) {
    free(_clientCert);
    _clientCert = nullptr;
  }
  if (_clientKey) {
    free(_clientKey);
    _clientKey = nullptr;
  }
  if (_caCert) {
    free(_caCert);
    _caCert = nullptr;
  }

  _cn[0] = '\0';
  _expiresAt = 0;
  _certVersion = 0;
  _latitude = 0.0f;
  _longitude = 0.0f;

  return true;
}

bool CertificateManager::startProvisioningMode(IWebServer *webServer) {
  _arduino->log("CertificateManager: Starting provisioning mode");

  if (!webServer) {
    setError("Web server not provided");
    return false;
  }

  _provisioningServer = webServer;

  // Disconnect any existing WiFi connections
  _wifi->disconnect();
  _arduino->delay(100);

  // Start WiFi in AP mode with explicit IP configuration
  char macStr[64];
  snprintf(macStr, sizeof(macStr), "TaraMeteoProv-%s", getLastMACOctet());

  _wifi->mode(2); // WIFI_AP

  // Configure AP with explicit IP address
  // Note: IPAddress is provided by Arduino.h in ESP32 builds
  // In unit tests, it's provided by test/mocks/Arduino.h
  IPAddress local_IP(192, 168, 4, 1);
  IPAddress gateway(192, 168, 4, 1);
  IPAddress subnet(255, 255, 255, 0);

  if (!_wifi->softAPConfig(local_IP, gateway, subnet)) {
    _arduino->log("CertificateManager: Failed to configure AP IP");
    setError("Failed to configure AP");
    return false;
  }

  if (!_wifi->softAP(macStr)) {
    _arduino->log("CertificateManager: Failed to start AP");
    setError("Failed to start AP");
    return false;
  }

  _arduino->delay(500); // Give AP time to start

  auto IP = _wifi->softAPIP();
  _arduino->log("===========================================");
  _arduino->logf("AP SSID: %s", macStr);
  // Note: IP.toString() might not work with mocks, so we format manually
  _arduino->log("AP IP: 192.168.4.1");
  _arduino->log("AP Password: (none - open network)");
  _arduino->log("Visit: http://192.168.4.1");
  _arduino->log("===========================================");

  setupProvisioningServer();

  _provisioningActive = true;
  _provisioningStartTime = _arduino->millis();

  _arduino->log("CertificateManager: HTTP server started and ready for requests");
  return true;
}

void CertificateManager::stopProvisioningMode() {
  if (_provisioningServer) {
    _provisioningServer->stop();
    _provisioningServer = nullptr;
  }
  _provisioningActive = false;
  _arduino->log("CertificateManager: Provisioning mode stopped");
}

void CertificateManager::handleProvisioningLoop() {
  if (_provisioningServer && _provisioningActive) {
    _provisioningServer->handleClient();

    // Check for timeout every 30 seconds
    static unsigned long lastCheck = 0;
    unsigned long now = _arduino->millis();
    if (now - lastCheck > 30000) {
      unsigned long elapsed = (now - _provisioningStartTime) / 1000;
      _arduino->logf("Provisioning active for %lu seconds, waiting for connection...", elapsed);

      // Show number of connected clients
      int clients = _wifi->softAPgetStationNum();
      _arduino->logf("Connected clients to AP: %d", clients);

      lastCheck = now;
    }
  }
}

void CertificateManager::setupProvisioningServer() {
  _provisioningServer->on("/", [this]() {
    _arduino->log("CertificateManager: Received GET request for /");
    handleRootRequest();
  });

  _provisioningServer->onPost("/provision", [this]() {
    _arduino->log("CertificateManager: Received POST request for /provision");
    handleProvisionRequest();
  });

  _provisioningServer->onNotFound([this]() {
    _arduino->logf("CertificateManager: 404 - Not found: %s", _provisioningServer->uri());
    _provisioningServer->send(404, "text/plain", "Not found");
  });

  _provisioningServer->begin();
  _arduino->log("CertificateManager: HTTP server started on port 80");
}

void CertificateManager::handleRootRequest() {
  const char *html = R"html(
<!DOCTYPE html>
<html>
<head>
    <title>TaraMeteo Provisioning</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body { font-family: Arial; margin: 40px; background: #f0f0f0; }
        .container { background: white; padding: 30px; border-radius: 10px; max-width: 600px; margin: 0 auto; }
        h1 { color: #2196F3; }
        input { width: 100%; padding: 10px; margin: 10px 0; font-size: 14px; box-sizing: border-box; }
        button { background: #2196F3; color: white; padding: 15px 30px; border: none; border-radius: 5px; cursor: pointer; font-size: 16px; }
        button:hover { background: #0b7dda; }
        .info { background: #e3f2fd; padding: 15px; border-radius: 5px; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="container">
        <h1>TaraMeteo Provisioning</h1>
        <div class="info">
            <strong>WiFi &amp; Location Setup</strong><br>
            <p>Certificates are pre-flashed. Enter your WiFi credentials and sensor location below.</p>
        </div>
        <form method="POST" action="/provision">
            <h2>WiFi Configuration</h2>
            <label><strong>WiFi SSID:</strong></label>
            <input type="text" name="wifi_ssid" required placeholder="your-wifi-network">

            <label><strong>WiFi Password:</strong></label>
            <input type="password" name="wifi_password" required placeholder="your-wifi-password">

            <h2>Location</h2>
            <label><strong>Latitude:</strong></label>
            <input type="number" name="latitude" required step="0.000001" min="-90" max="90" placeholder="45.504">

            <label><strong>Longitude:</strong></label>
            <input type="number" name="longitude" required step="0.000001" min="-180" max="180" placeholder="-73.617">

            <button type="submit">Provision Device</button>
        </form>
    </div>
</body>
</html>
)html";

  _provisioningServer->send(200, "text/html", html);
}

void CertificateManager::handleProvisionRequest() {
  _arduino->log("CertificateManager: Received provisioning request");

  // Validate required WiFi fields
  if (!_provisioningServer->hasArg("wifi_ssid") || !_provisioningServer->hasArg("wifi_password")) {
    sendResponse(400, "Missing required fields: wifi_ssid and wifi_password");
    return;
  }

  const char *wifiSsid = _provisioningServer->arg("wifi_ssid");
  const char *wifiPassword = _provisioningServer->arg("wifi_password");

  if (strlen(wifiSsid) == 0 || strlen(wifiPassword) == 0) {
    sendResponse(400, "WiFi SSID and password must not be empty");
    return;
  }

  // Validate location fields
  if (!_provisioningServer->hasArg("latitude") || !_provisioningServer->hasArg("longitude")) {
    sendResponse(400, "Missing required fields: latitude and longitude");
    return;
  }

  float latitude = atof(_provisioningServer->arg("latitude"));
  float longitude = atof(_provisioningServer->arg("longitude"));

  if (latitude < -90.0f || latitude > 90.0f) {
    sendResponse(400, "Invalid latitude: must be between -90 and 90");
    return;
  }
  if (longitude < -180.0f || longitude > 180.0f) {
    sendResponse(400, "Invalid longitude: must be between -180 and 180");
    return;
  }

  // Store location in NVS
  _latitude = latitude;
  _longitude = longitude;
  _prefs.putFloat("latitude", _latitude);
  _prefs.putFloat("longitude", _longitude);

  // Store WiFi credentials
  bool wifiProvisioned = false;
#ifndef UNIT_TEST
  if (_wifiManager && _wifiManager->storeCredentials(wifiSsid, wifiPassword)) {
    _arduino->log("CertificateManager: WiFi credentials stored successfully");
    wifiProvisioned = true;
  } else {
    sendResponse(400, "Failed to store WiFi credentials");
    return;
  }
#else
  if (_wifiManager) {
    _arduino->log("CertificateManager: WiFi credentials stored successfully (mock)");
    wifiProvisioned = true;
  }
#endif

  if (wifiProvisioned) {
    sendResponse(200, "Provisioned successfully! WiFi and location stored. Rebooting in 3 seconds...");
    _arduino->delay(3000);
    stopProvisioningMode();
    _arduino->restart();
  } else {
    sendResponse(400, "WiFi manager not available");
  }
}

void CertificateManager::sendResponse(int code, const char *message) {
  StaticJsonDocument<256> doc;
  doc["status"] = (code == 200) ? "success" : "error";
  doc["message"] = message;
  if (code == 200) {
    doc["cn"] = _cn;
  }

  char response[512];
  serializeJson(doc, response, sizeof(response));

  _provisioningServer->send(code, "application/json", response);
}

const char *CertificateManager::getLastMACOctet() {
  static char macStr[5];
  uint8_t mac[6];
  _wifi->macAddress(mac);
  snprintf(macStr, sizeof(macStr), "%02X%02X", mac[4], mac[5]);
  return macStr;
}

void CertificateManager::setError(const char *error) {
  strncpy(_lastError, error, sizeof(_lastError) - 1);
  _lastError[sizeof(_lastError) - 1] = '\0';
  _arduino->logf("CertificateManager: ERROR - %s", _lastError);
}

void CertificateManager::clearClientCredentials() {
  free(_clientCert);
  free(_clientKey);
  _clientCert = nullptr;
  _clientKey = nullptr;
}

void CertificateManager::clearCACertificate() {
  free(_caCert);
  _caCert = nullptr;
}
