[project]
name = "tarameteo"
version = "0.0.0"
description = "Weather station firmware"
authors = [
    {name = "Marc Tardif", email = "marc@taram.ca"}
]
readme = "README.rst"
requires-python = ">=3.12,<4.0"
dependencies = [
    "platformio (>=6.1.18,<7.0.0)"
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
